name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    outputs:
      artifacts:
        description: List of produced artifacts, each on a new line
        value: ${{ jobs.build.outputs.artifacts }}
      primary-artifact:
        description: Path to the primary artifact
        value: ${{ jobs.build.outputs.primary-artifact }}
      secondary-artifacts-glob:
        description: Glob of paths to secondary artifacts
        value: ${{ jobs.build.outputs.secondary-artifacts-glob }}

jobs:
  build:
    name: Gradle build
    env:
      ARTIFACTS: |
        packages/single/build/libs/MapModCompanion.jar
        bungee/build/libs/MapModCompanion-Bungee.jar
        spigot/build/libs/MapModCompanion-Spigot.jar
      PRIMARY_ARTIFACT: packages/single/build/libs/MapModCompanion.jar
      SECONDARY_ARTIFACTS_GLOB: (bungee|spigot)/build/libs/MapModCompanion-*.jar
    outputs:
      artifacts: ${{ env.ARTIFACTS }}
      primary-artifact: ${{ env.PRIMARY_ARTIFACT }}
      secondary-artifacts-glob: ${{ env.SECONDARY_ARTIFACTS_GLOB }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Determine target Spigot version
        id: target
        run: |
          TARGET=${{ inputs.spigot-target }}
          [[ -z "$TARGET" ]] && TARGET=$(tail -n1 VERSIONS.txt)
          echo "spigot-version=$TARGET" >> $GITHUB_OUTPUT
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -Pversion=${{ inputs.version }}
            -Pspigot_version=${{ steps.target.outputs.spigot-version }}
            -PprotocolLib_version=4.2.1
      - uses: actions/upload-artifact@v3
        with:
          name: gradle-build
          path: ${{ env.ARTIFACTS }}
