name: CurseForge release

on: workflow_dispatch

jobs:
  version:
    name: Detect version
    uses: ./.github/workflows/version.yml
  build:
    name: Build
    needs: version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.version }}
  upload:
    name: Upload
    needs:
      - version
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: gradle-build
      - uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          game_endpoint: "bukkit"
          project_id: "674380"
          release_type: ${{ needs.version.outputs.release-type  }}
          display_name: ${{ needs.version.outputs.version }}
          changelog: |
            Changelog is available on
            [GitHub](https://github.com/turikhay/MapModCompanion/releases/tag/v${{ needs.version.outputs.version }})
          file_path: ${{ needs.build.outputs.primary-artifact }}
